import { Store, StoreStats, DashboardStats, Order, SalesData } from './api';

export const mockStores: Store[] = [
  {
    id: 'store-1',
    name: 'Fashion Hub',
    platform: 'WOOCOMMERCE',
    storeUrl: 'fashionhub.com',
    isActive: true,
    lastSyncAt: new Date().toISOString(),
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'store-2',
    name: 'Tech Gadgets',
    platform: 'SHOPIFY',
    storeUrl: 'techgadgets.myshopify.com',
    isActive: true,
    lastSyncAt: new Date().toISOString(),
    createdAt: '2024-01-05T00:00:00Z',
  },
  {
    id: 'store-3',
    name: 'Home Decor',
    platform: 'WOOCOMMERCE',
    storeUrl: 'homedecor.pk',
    isActive: false,
    lastSyncAt: '2024-01-08T00:00:00Z',
    createdAt: '2024-01-08T00:00:00Z',
  },
  {
    id: 'store-4',
    name: 'Sports Zone',
    platform: 'SHOPIFY',
    storeUrl: 'sportszone.myshopify.com',
    isActive: true,
    lastSyncAt: new Date().toISOString(),
    createdAt: '2024-01-10T00:00:00Z',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalRevenue: 125840,
  totalOrders: 1247,
  pendingOrders: 23,
  totalProfit: 37520,
  profitMargin: 29.8,
  activeProducts: 156,
  lowStockProducts: 8,
};

export const mockStoreStats: Record<string, StoreStats> = {
  'store-1': {
    totalOrders: 456,
    pendingOrders: 12,
    totalRevenue: 45600,
    totalProfit: 13680,
    profitMargin: 30,
    fulfilledOrders: 444,
    fulfillmentRate: 97.4,
  },
  'store-2': {
    totalOrders: 389,
    pendingOrders: 5,
    totalRevenue: 52300,
    totalProfit: 15690,
    profitMargin: 30,
    fulfilledOrders: 384,
    fulfillmentRate: 98.7,
  },
  'store-3': {
    totalOrders: 123,
    pendingOrders: 0,
    totalRevenue: 12400,
    totalProfit: 3720,
    profitMargin: 30,
    fulfilledOrders: 123,
    fulfillmentRate: 100,
  },
  'store-4': {
    totalOrders: 279,
    pendingOrders: 6,
    totalRevenue: 15540,
    totalProfit: 4410,
    profitMargin: 28.4,
    fulfilledOrders: 273,
    fulfillmentRate: 97.8,
  },
};

export const mockSalesData: SalesData[] = [
  { date: 'Mon', revenue: 4200, orders: 28, profit: 1260 },
  { date: 'Tue', revenue: 3800, orders: 24, profit: 1140 },
  { date: 'Wed', revenue: 5100, orders: 35, profit: 1530 },
  { date: 'Thu', revenue: 4600, orders: 31, profit: 1380 },
  { date: 'Fri', revenue: 6200, orders: 42, profit: 1860 },
  { date: 'Sat', revenue: 7800, orders: 52, profit: 2340 },
  { date: 'Sun', revenue: 6100, orders: 41, profit: 1830 },
];

export const mockOrders: Order[] = [
  {
    id: 'ord-1',
    externalOrderId: '10234',
    storeId: 'store-1',
    store: mockStores[0],
    customerEmail: 'ali.khan@gmail.com',
    status: 'PENDING',
    total: 89.99,
    profit: 26.99,
    createdAt: new Date().toISOString(),
    trackingNumber: undefined,
  },
  {
    id: 'ord-2',
    externalOrderId: '10233',
    storeId: 'store-2',
    store: mockStores[1],
    customerEmail: 'sarah.ahmed@hotmail.com',
    status: 'PENDING',
    total: 149.99,
    profit: 44.99,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    trackingNumber: undefined,
  },
  {
    id: 'ord-3',
    externalOrderId: '10232',
    storeId: 'store-1',
    store: mockStores[0],
    customerEmail: 'hassan.malik@yahoo.com',
    status: 'PROCESSING',
    total: 59.99,
    profit: 17.99,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    trackingNumber: undefined,
  },
  {
    id: 'ord-4',
    externalOrderId: '10231',
    storeId: 'store-4',
    store: mockStores[3],
    customerEmail: 'fatima.shah@gmail.com',
    status: 'SHIPPED',
    total: 199.99,
    profit: 59.99,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    trackingNumber: 'CJ2024011234567',
  },
  {
    id: 'ord-5',
    externalOrderId: '10230',
    storeId: 'store-2',
    store: mockStores[1],
    customerEmail: 'usman.raza@outlook.com',
    status: 'SHIPPED',
    total: 299.99,
    profit: 89.99,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    trackingNumber: 'CJ2024011234568',
  },
  {
    id: 'ord-6',
    externalOrderId: '10229',
    storeId: 'store-1',
    store: mockStores[0],
    customerEmail: 'maria.khan@gmail.com',
    status: 'DELIVERED',
    total: 79.99,
    profit: 23.99,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    trackingNumber: 'CJ2024011234569',
  },
  {
    id: 'ord-7',
    externalOrderId: '10228',
    storeId: 'store-4',
    store: mockStores[3],
    customerEmail: 'bilal.ahmed@hotmail.com',
    status: 'DELIVERED',
    total: 129.99,
    profit: 38.99,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    trackingNumber: 'CJ2024011234570',
  },
  {
    id: 'ord-8',
    externalOrderId: '10227',
    storeId: 'store-2',
    store: mockStores[1],
    customerEmail: 'ayesha.siddiqui@yahoo.com',
    status: 'PENDING',
    total: 249.99,
    profit: 74.99,
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    trackingNumber: undefined,
  },
];

export const mockOrderStats = {
  pending: mockOrders.filter(o => o.status === 'PENDING').length,
  processing: mockOrders.filter(o => o.status === 'PROCESSING').length,
  shipped: mockOrders.filter(o => o.status === 'SHIPPED').length,
  delivered: mockOrders.filter(o => o.status === 'DELIVERED').length,
};
